name: weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.2.0
  material_floating_search_bar: ^0.3.7
  riverpod: ^2.2.0
  shared_preferences: ^2.0.17
  font_awesome_flutter: ^10.4.0
  device_preview: ^1.1.0
  url_launcher: ^6.1.9
  sizer: ^2.0.15
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  meta: ^1.8.0
  state_notifier: 0.7.2+1
  connectivity_plus: 2.3.0
  collection: 1.16.0
  http: 0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2
  mockito: 5.2.0
  build_runner: 2.1.11

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
